name: dart_grpc_example
description: A simple gRPC example
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0

dependencies: 
  grpc: ^3.0.0
  image: ^3.0.2
  protobuf: ^2.0.0
